### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by mukeshwani** [robmarshall/tns-gatsby#10]
Hi I'm experimenting with this and once I run gatsby develop I get this syntax error:

  Error: C:\Users\mukesh\apps\webhostingforbeginners\gatsby\create\post.js:26
              const primaryCatId = post?.categories?.nodes[0]?.databaseId || false
                                        ^
  SyntaxError: Unexpected token .

Any help is appreciated.

**Comment by robmarshall** [comment]
Sounds like you are running on an old node that doesn't support optional
chaining.

**Comment by mukeshwani** [comment]
Hi, thanks for the quick feedback. I upgraded Node to the latest version. I'm using Windows and the version is now 12.18.3, however I still get the same error. Is there a module that I may be missing?

Thanks,
Mukesh

**Comment by robmarshall** [comment]
The latest node is 14.8. give that a try.

**Comment by mukeshwani** [comment]
Hi, yes that worked. I had installed the LTS version, but updating to Current Latest version removed that error. I did get another error but I will try to debug that prior to posting here. Thanks for the quick response!
