### ISSUE TITLE
Cannot query field "seo" on type "WpPost".

### ISSUE THREAD

**Issue by mukeshwani** [robmarshall/tns-gatsby#11]
Hi Rob. I am getting an error that the field seo can't be found. I thought it would be due to not having the Yoast plugin, and I've added that now still same error. Just to see if it is looking for a custom field, I've added 'seo' as a custom field with a dummy text to both the page and posts. I've check on GraphiQL and I don't see 'seo' as part of the fields we can query. What could I be missing?

**Comment by robmarshall** [comment]
Hey, I need to update the readme for this. You will need to add this plugin as well: https://github.com/ashhitch/wp-graphql-yoast-seo:

**Comment by mukeshwani** [comment]
Ah got it. I was reading the docs on WPGraphQL and found the code snippet to expose custom fields to GraphQL and so I added the action to hook into graphql_register_types. I'll add the plugin you mentioned as well. Thanks!!
